### PR TITLE
Fix exception if no SITE_ID is set

### PR DESCRIPTION
**Pull request by Celant**
If no SITE_ID is in the settings file, the `Site.objects.get_current()` method should be called with the request to correctly lookup the current site.

### CODE REVIEW

**Comment by Celant** [comment]
CI won't pass, because the project has no setup.py anymore :) (Is that something we can work around?)

**Comment by abe312** [comment]
I think I removed setup.py in the last commit as it's only required by me to submit code to PyPI.
you can retrieve it from going to previous git commit ;) 
Now, I think SITE_ID is required (different id's for different domains/subdomains).
I wouldn't push the code to PyPI without some testing (as the current version is working just fine).

**Comment by Celant** [comment]
This code needs a little more testing on my end :) Django doesn't require a SITE_ID in the settings file, as long as get_current is called with a request parameter.

I'll do some more testing on this side, then update the PR

**Comment by abe312** [comment]
Alright :)
Also, try giving detailed instructions on how to get subdomains fully working.
As of now, with help of the following links *anyone* could configure the subdomains: 

http://stackoverflow.com/questions/25468676/django-sites-model-what-is-and-why-is-site-id-1
http://stackoverflow.com/questions/38284661/using-django-subdomain-and-it-says-localhost-does-not-belong-to-the-domain-examp
http://stackoverflow.com/questions/11372064/django-registration-how-do-i-change-example-com-in-the-email
http://stackoverflow.com/questions/12289148/where-do-i-set-the-domain-for-my-django-sites-framework-site-when-i-only-have-o/12289245#12289245
http://stackoverflow.com/questions/11814059/site-matching-query-does-not-exist
http://stackoverflow.com/questions/39294559/django-subdomains-config-localhost
https://wellfire.co/learn/multi-tennancy-in-django-using-subdomains/
https://django-subdomains.readthedocs.io/en/latest/

**Comment by abe312** [comment]
Closing the PR, I'll update middleware when I get time. 
Todos: testing for 2.0 and 2.1 and removing python 2 for django 2.0 and 2.1

**Comment by abe312** [comment]
check out the new released version (works till django3.0.2 and backwards compatible from django1.11LTS)

**Pull request closed without merging**
