### PR TITLE
Update django.core.urlresolvers to django.urls for django 2.0 compatability

### PR DESCRIPTION
**Pull request by riconnon**

### CODE REVIEW

**Comment by abe312** [comment]
would this be backwards compatible?

**Comment by riconnon** [comment]
@abe312 This change is compatible back to Django 1.10.x
Unfortunately I closed this PR because I realised I'd made it against the wrong fork. I stopped using your fork because you removed important content (setup.py) from the repo for seemingly no reason

**Comment by abe312** [comment]
It's still available in the previous commit. I thought its only use is to submit the code to PyPI. I now realize that it's required to pass some tests on GitHub.
Have you tested it to the previous version of django (1.10.x)? If yes, then which versions? Let's do some testing and push the code to PyPI.

**Comment by bitcity** [comment]
@riconnon Which repo are you using for subdomains (that includes your PR for 2.0 compatibility) ?

**Comment by riconnon** [comment]
@bitcity I'm actually moving away from using subdomains because of changes in my application.
There are a lot of forks of this and different ones have different fixes. Shame there's no canonical upstream.

**Comment by bitcity** [comment]
True. I'll end up moving away as well in the future because none of them are actively developed. I came across https://github.com/jazzband/django-hosts/ which might be a suitable alternative for some of the users here. 

Would be glad to know what others are using.

**Comment by abe312** [comment]
check out the latest release (works till django3.0.2 and backwards compatible from django1.11LTS)
Also, we're planning on supporting this for all future django LTS versions!

**Pull request closed without merging**
